{
  DVC_TYPE: ["String"],
  DVC_NAME: ["String"],
  DVC_ADDRESS: ["Object", "Ip"],
  DVC_RECEIPT_TIME: ["Datetime"],
  START_TIME: ["Datetime"],
  END_TIME: ["Datetime"],
  DVC_EVENT_CATEGORY: ["String"],
  SEVERITY: ["Integer"],
  PRIORITY: ["String"],
  DVC_PROCESS_NAME: ["String"],
  EVENT_TYPE: ["String"],
  TRANS_PROTOCOL: ["String"],
  SRC_ADDRESS: ["Object", "Ip"],
  DEST_ADDRESS: ["Object", "Ip"],
  SRC_PORT: ["Integer"],
  DEST_PORT: ["Integer"],
  SRC_MAC_ADDRESS: ["Object", "Mac"],
  DEST_MAC_ADDRESS: ["Object", "Mac"],
  Trans:{
    SRC_ADDRESS: ["Object", "Ip"],
    DEST_ADDRESS: ["Object", "Ip"],
    SRC_PORT: ["Integer"],
    DEST_PORT: ["Integer"]
  },
  PACKETS_IN: ["Long"],
  PACKETS_OUT: ["Long"],
  BYTES_IN: ["Long"],
  BYTES_OUT: ["Long"],
  DURATION: ["Long"],
  CONNID: ["String"],
  POLICY: ["String"],
  OP: ["String"],
  MESSAGE: ["String"]
}